name: model_viewer_pro
description: Interactive 3D models in Flutter. Full runtime control over mesh visibility, colors, cameras, animations, and lighting. Built on model_viewer_plus.
version: 1.0.3
homepage: https://github.com/Abdullatariq47/model_viewer_pro
repository: https://github.com/Abdullatariq47/model_viewer_pro
issue_tracker: https://github.com/Abdullatariq47/model_viewer_pro/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  model_viewer_plus: ^1.10.0
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0